#!/usr/bin/env bash
# docker_api_test.sh
# Tests against the Docker socket API directly via curl.
# Each test section is self-contained and cleans up after itself.

set -euo pipefail

DOCKER_SOCK="/var/run/docker.sock"
OUTPUT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_VAR_NAMES_FILE="${OUTPUT_DIR}/env_var_names.txt"

# ─── helpers ──────────────────────────────────────────────────────────────────

log()  { echo "[docker_api_test] $*"; }
fail() { echo "[docker_api_test] FAIL: $*" >&2; exit 1; }

docker_api() {
  # Usage: docker_api <method> <path> [body]
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -s --unix-socket "$DOCKER_SOCK" \
      -X "$method" \
      -H "Content-Type: application/json" \
      -d "$body" \
      "http://localhost${path}"
  else
    curl -s --unix-socket "$DOCKER_SOCK" \
      -X "$method" \
      "http://localhost${path}"
  fi
}

container_remove() {
  local id="$1"
  docker_api DELETE "/v1.41/containers/${id}?force=true" >/dev/null 2>&1 || true
}

# ─── preflight ────────────────────────────────────────────────────────────────

[[ -S "$DOCKER_SOCK" ]] || fail "Docker socket not found at $DOCKER_SOCK"
docker_api GET "/v1.41/info" | jq -e '.ID' >/dev/null \
  || fail "Cannot reach Docker daemon via socket"
log "Docker daemon reachable."

# ─── Test: Runtime environment variable name audit ────────────────────────────
#
# Creates a container that mounts the host /proc as /hostproc (read-only) and
# scans each process's environ file for variable NAMES (not values) that match
# security-sensitive keywords: KEY, TOKEN, SECRET, API, AUTH.
# Results are written to env_var_names.txt for review.
# ──────────────────────────────────────────────────────────────────────────────

log "=== Runtime environment variable name audit ==="

AUDIT_IMAGE="alpine:latest"

# Pull image if not present (best-effort; container creation will fail clearly if missing)
log "Ensuring image ${AUDIT_IMAGE} is available..."
docker_api POST "/v1.41/images/create?fromImage=alpine&tag=latest" >/dev/null 2>&1 || true

AUDIT_SCRIPT='#!/bin/sh
OUTPUT=/output/env_var_names.txt
: > "$OUTPUT"
for pid in $(ls /hostproc/ | grep -E "^[0-9]+$" | head -30); do
  cmdline=$(cat /hostproc/$pid/cmdline 2>/dev/null | tr "\0" " ")
  vars=$(cat /hostproc/$pid/environ 2>/dev/null | tr "\0" "\n" \
         | grep -iE "KEY|TOKEN|SECRET|API|AUTH" | cut -d= -f1)
  if [ -n "$vars" ]; then
    echo "PID $pid ($cmdline): $vars" >> "$OUTPUT"
  fi
done
echo "Audit complete. Results in $OUTPUT"
cat "$OUTPUT"
'

# Build the container config
CONTAINER_CONFIG=$(jq -n \
  --arg image "$AUDIT_IMAGE" \
  --arg script "$AUDIT_SCRIPT" \
  '{
    Image: $image,
    Cmd: ["sh", "-c", $script],
    HostConfig: {
      Binds: [
        "/proc:/hostproc:ro",
        "/tmp/docker_audit_output:/output"
      ]
    }
  }')

# Prepare host-side output directory
mkdir -p /tmp/docker_audit_output

# Create container
log "Creating audit container..."
CREATE_RESP=$(docker_api POST "/v1.41/containers/create" "$CONTAINER_CONFIG")
CONTAINER_ID=$(echo "$CREATE_RESP" | jq -r '.Id // empty')
[[ -n "$CONTAINER_ID" ]] || fail "Failed to create audit container: $CREATE_RESP"
log "Container created: ${CONTAINER_ID:0:12}"

# Start container
log "Starting audit container..."
docker_api POST "/v1.41/containers/${CONTAINER_ID}/start" >/dev/null

# Wait for container to finish (timeout 30 s)
log "Waiting for audit to complete..."
WAIT_RESP=$(curl -s --unix-socket "$DOCKER_SOCK" \
  -X POST \
  --max-time 30 \
  "http://localhost/v1.41/containers/${CONTAINER_ID}/wait")
EXIT_CODE=$(echo "$WAIT_RESP" | jq -r '.StatusCode // 1')
log "Container exited with status: ${EXIT_CODE}"

# Collect stdout logs from container
LOGS=$(curl -s --unix-socket "$DOCKER_SOCK" \
  "http://localhost/v1.41/containers/${CONTAINER_ID}/logs?stdout=true&stderr=true" \
  | strings 2>/dev/null || true)

# Copy result out of the shared volume path
if [[ -f /tmp/docker_audit_output/env_var_names.txt ]]; then
  cp /tmp/docker_audit_output/env_var_names.txt "$ENV_VAR_NAMES_FILE"
  log "env_var_names.txt written to: $ENV_VAR_NAMES_FILE"
else
  # Fallback: parse logs for audit lines
  {
    echo "# env_var_names.txt — generated by docker_api_test.sh runtime audit"
    echo "# Captured variable NAMES only (no values) matching KEY|TOKEN|SECRET|API|AUTH"
    echo "# Host /proc scanned from container via /hostproc:ro mount"
    echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "$LOGS"
  } > "$ENV_VAR_NAMES_FILE"
  log "env_var_names.txt written from container logs."
fi

# Cleanup
container_remove "$CONTAINER_ID"
rm -rf /tmp/docker_audit_output

[[ "$EXIT_CODE" -eq 0 ]] || fail "Audit container exited with non-zero status: $EXIT_CODE"

log "=== Audit test PASSED ==="
log "Results saved to: $ENV_VAR_NAMES_FILE"
