#!/usr/bin/env python3
"""
snapshot_runtime.py

Captures all current environment variables and writes them to .env.runtime
in KEY=VALUE format for reproducibility in CI and local debugging.

Sensitive variable values (API keys, tokens, passwords, secrets) are
automatically redacted so the file is safe to commit.

Usage:
    python scripts/snapshot_runtime.py [--output .env.runtime]
"""

import argparse
import os
import re
from datetime import datetime, timezone

# Patterns in variable names that indicate a secret value
_SECRET_NAME_PATTERNS = re.compile(
    r"(API[_\-]?KEY|SECRET|PASSWORD|PASSWD|TOKEN|CREDENTIAL|PRIVATE[_\-]?KEY"
    r"|ACCESS[_\-]?KEY|AUTH[_\-]?KEY|SIGNING[_\-]?KEY|ENCRYPTION[_\-]?KEY"
    r"|CLIENT[_\-]?SECRET|OAUTH|BEARER|SESSION[_\-]?KEY)",
    re.IGNORECASE,
)


def is_sensitive(key: str) -> bool:
    return bool(_SECRET_NAME_PATTERNS.search(key))


def snapshot_env(output_path: str) -> None:
    env_vars = os.environ.items()

    lines = [
        "# Generated by scripts/snapshot_runtime.py",
        f"# Timestamp: {datetime.now(timezone.utc).isoformat()}",
        "# Sensitive values are redacted (<REDACTED>) for safe storage.",
        "",
    ]

    redacted_count = 0
    for key, value in sorted(env_vars):
        if is_sensitive(key):
            lines.append(f"{key}=<REDACTED>")
            redacted_count += 1
        else:
            # Escape newlines so the file stays parseable line-by-line
            escaped = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")
            lines.append(f"{key}={escaped}")

    content = "\n".join(lines) + "\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    total = len(lines) - 4  # subtract header lines
    print(
        f"Wrote {total} environment variables to {output_path} "
        f"({redacted_count} redacted as sensitive)"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Snapshot current environment variables to a .env file."
    )
    parser.add_argument(
        "--output",
        default=".env.runtime",
        help="Path to write the environment snapshot (default: .env.runtime)",
    )
    args = parser.parse_args()

    snapshot_env(args.output)


if __name__ == "__main__":
    main()
